# Generated by Django 3.2 on 2021-04-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('BookingInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.bookinginfo')),
            ],
        ),
    ]
